/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description Bad Request Error Schema */
    Bad_Request: {
      /**
       * @description response status
       * @example 400
       */
      status: Record<string, never>;
      /**
       * @description Error message
       * @example Bad Request
       */
      message: string;
    };
    /** @description Unauthorized Error Schema */
    Unauthorized: {
      /**
       * @description response status
       * @example 401
       */
      status: Record<string, never>;
      /**
       * @description Error message
       * @example Unauthorized
       */
      message: string;
    };
    /** @description Internal Server Error Schema */
    Internal_Server_Error: {
      /**
       * @description response status
       * @example 500
       */
      status: Record<string, never>;
      /**
       * @description Error message
       * @example Internal Server Error
       */
      message: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
