/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description Timeline Schema */
    Timeline: {
      posts?: (external["post.yaml"]["components"]["schemas"]["Post"])[];
      /** @description whether there is next page */
      has_next?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export interface external {
  "post.yaml": Record<string, never>
}

export type operations = Record<string, never>;
