/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description User Schema */
    User: {
      user_id?: number;
      /**
       * @description This id can be modified by user
       * @example getupmax
       */
      account_id: string;
      /** @example sample@example.com */
      email: string;
      /** @example tasuku_nakagawa */
      display_name: string;
      /** @example coffee lover */
      introduction?: string;
      /**
       * @description icon url
       * @example https://example.com/icon.png
       */
      icon_url?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
