name: "Frontend app build check"

"on":
  pull_request:
    types: [opened, synchronize]
    paths:
      - frontend/**/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./frontend

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
      - name: Generate schema and api client
        run: npm run generate
      - name: Build app
        run: npm run build
