name: Check swagger syntax is valid
"on":
  pull_request:
    types: [opened, synchronize]
    paths:
      - swagger/**/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./swagger

jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install swagger-cli
        run: |
          npm install -g swagger-cli

      - name: Combine Multiple Swagger Files
        run: |
          swagger-cli bundle schema/main.yaml --outfile docs/swagger.yaml --type yaml --format 3
